---
title: At Visible Data *we* do...
author: Martin John Hadley
date: '2018-03-29'
slug: at-visible-data-we-do
categories:
  - meta
tags:
  - meta
draft: no
editor_options: 
  chunk_output_type: console
banner: "img/blog-images/header-images/2018-03-29_at-visible-data-we-do.png"
---

There are so many awesome folks in the [#rstats](https://twitter.com/search?src=typd&q=%23rstats) community that I respect and have learned from over the last 3 years, I owe a lot of my development and growth to the great community behind [#rstats](https://twitter.com/search?src=typd&q=%23rstats). It's been particularly rewarding and uplifting to read personal stories, conflicts with imposters syndrome and struggles with mental health episodes. There are some particularly inspiring or interesting posts or ideas that I've found particularly useful, and will maintain a collection of [humans and their stories](/humans-and-their-stories) at the bottom of this post.

**Visible Data Ltd** is all about encouraging/consulting on how folks can be open and transparent about their research, analyses, data and the workflows behind these - and this necessarily includes being candid about personal struggles and the complexities of living that often get smoothed over any ignored.

As of March 2018, **Visible Data Ltd** is a single-person consultancy. It's just me ([\@martinjhnhadley](http://twitter.com/martinjhnhadley)) working on it. Something that really challenges me about that is deciding how to write about what Visible Data is and what it does. In the future, I plan to collaborate with a few folks I know on consultancy projects and I'm really excited about that. Because of that I want to prepare a consultancy that is setup to have multiple personalities in it and respect all their contributions and ideas, also as a genderqueer human I find it particularly important to use non-exclusionary language. This leads to the slightly uncomfortable requirement to use the phrase

<blockquote>
At Visible Data **we** do...
</blockquote>

This phrasing has significant commercial benefits, it makes the consultancy seem more legitimate but it also feels weird when I write about an opinion/view of the consultancy which (at present) is exclusively mine. I felt enough discomfort about this to run a Twitter poll, which I was delighted to have a ~7% engagement rate with (20 votes from 293 impressions):

<center>
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">I run a <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> consultancy that&#39;s currently just me, thought might bring other folks on board in the future... if in blogs etc I write <br><br>&quot;At Visible Data *we* do X&quot; <br><br>how does that sound?</p>&mdash; Martin John Hadley (@martinjhnhadley) <a href="https://twitter.com/martinjhnhadley/status/976835348318875648?ref_src=twsrc%5Etfw">March 22, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</center>

A good 85% of folks agreed that it's fine to keep the inclusive pronoun, and I think that makes sense. I'm going to continue to indulge this desire to legitimise the consultancy with the inclusive pronoun and to keep it a space that others can join in the future and feel represented.

## Humans and their stories from #rstats {#humans-and-their-stories}

This is no where near a comprehensive collection of resources, and it is extremely scant as of now because I wanted to get this post out and not spend months collating examples first.

- R4DS Slack Group: This awesome Slack community is run by Jess Meagen ([\@kierisi](http://twitter.com/kierisi)), folks are encouraged to join and collaboratively work through the excellent [R for Data Science](http://r4ds.had.co.nz/) book. One thing I really enjoy about this community is the "wins" section, where folks can share their wins (when something suddenly clicks or they simplified some code). Here's the best link to find out more: [https://www.jessemaegan.com/post/r4ds-the-next-iteration/](https://www.jessemaegan.com/post/r4ds-the-next-iteration/)

- Yihui Xie's career story: Yihui recanted an extremely [open and honest](https://yihui.name/en/2018/02/career-crisis/) history of their career and the crises they experienced as they moved between jobby jobs and open source work.