---
title: Advent review 2018
author: ''
date: '2018-11-27'
slug: advent-review-2018
categories: []
tags: []
draft: true
editor_options: 
  chunk_output_type: console
---

Blog items:

1. Use Projects and `here` all the time (promotional)

2. Use namer

3. Pipes are syntactic suger

4. Use + NULL in `ggplot2`

5. DOI! Or else. DOI to BIBTEX.

6 Promotional leaflet, highcharter etc are htmlwidges 

7. Use tidyverse rather than dplyr

8. `forcats` makes life so much easier for reordering ggplot features

9. Use `stylr` and `lintr`

21. Process free-text gender responses with https://github.com/ropenscilabs/gendercoder

10. If you're doing GIS and you haven't started using the `sf` package, switch now!

11. Xaringan is the best option for slides, it massively helps improve the look and feel of the work I do

12. Consider accessibility when writing blogposts a la https://r-resources.massey.ac.nz/rmarkdown/


[13 Promotional]: `visNetwork` is incredibly slow at doing layouts! Always use `visIgraphLayout`

-----



18. `shiny` controls dependend on data need to be made in the server

12. My spread -> gather example



```{r}
library("tidyverse")
library("fivethirtyeight")

tarantino %>%
  filter(!is.na(word)) %>%
  count(word, movie) %>%
  spread(movie, n, fill = 0) %>%
  gather(movie, count, 2:ncol(.))%>%
  arrange(movie, word) %>%
  head()
```





14. Use `my_data %>% View(title = "just imported")`

16. `usethis` massively simplifies project development.

17. `rfigshare` is slightly frustrating to use, here's the cheat.



19. You're showing your age if you're still using shinyUI() and `shinyServer` 

[20 Promotional]. Leaflet in shiny apps requires z-index manipulation (see my htmlwidgets course)



22. Bookdown for anything longer than a few paragraphs!

23. Include your ORCID number in package DESCRIPTION files

24. Sometimes you need a pick-me up. Try out https://github.com/rladies/praise (MERRY CHRISTMAS)







