---
title: "Group Training from Visible Data (our offices)"
description: "Group Training from Visible Data (our offices)"
keywords: ["Training"]
---

<h3>What are the benefits of off-site training?</h3>

<div class='row'>

<div class='col-lg-10'>

<ul>

<li>If your team is distributed across multiple sites it can be really difficult to decide where to hold training on company sites. 
<br>
<strong>Dedicated off-site training sites are neutral territory (and Visible Data has <i>lots</i> of hotels nearby `r emo::ji("wave")`)</strong></li>


<li>Re-purposing a conference room at your office for multiple day training courses is often difficult, there's a temptation to break the training up over multiple weeks or over lunch.
<br>
<strong>Using a dedicated training space means you can easily book dedicated multi-day courses.</strong></li>

<li>Using a re-purposed conference room in your building is not going to put your team in the mindset to learn, folks may well be distracted thinking about what they're usually in the room for.
<br>
<strong>Off-site training helps put your team in the mindset to learn.</strong></li>

<li>Training on-site is often disrupted by colleagues being able to physically barge into rooms and "just check one thing."
<br>
<strong>Distractions are massively reduced when using a dedicated off-site training space.</strong></li>

</ul>

</div>

<div class='col-lg-2'>
<p></p>
<center>
<a href="#booking-form" class="btn btn-success btn-block" role="button">Book now</a>
</center>
  
</div>

</div>


<div class='row'>

<div class='col-sm-7'>

<h3>Why train at our offices?</h3>

<ul>
<li>
**We're located in Bristol City Centre.** 
<br>
Bristol has great transport links, it's also a beautiful and vibrant city to explore at the end of the training day.</li>
<li>
**Accessibility matters to us.**
<br>
Our training facilities have step-free access and we're happy to work with you and make reasonable adjustments. Read about our building's accessibility [below](#accessibility).</li>
<li>
**We use a dedicated, comfortable training room.**
<br>
We've set our max number at 15 to assure comfort, you will not be packed in line sardines.</li>
<li>
**All our training courses are BYOD (Bring Your Own Device).**
<br>
You'll learn how to do stuff with <strong>your</strong> (<i>work</i>) machine.</li>
<li>
**We've got extension cables for your laptops.**
<br>
You do need to bring your own chargers.</li>
<li>**There's coffee. And tea. And Wi-fi.**</li>
<li>**We provide lunch from Pret-A-Manger!**
<br>
Before the training day we'll agree what you'd like from the <a href='http://pret-files.azureedge.net/pretamanger-uk/Pret_Delivers/Delivery_Lunch_Menu.pdf' target='_blank'>lunch platter menu.</a>
</li>
</ul>

</div>

<div class='col-sm-5'>
<br>
<br>
<center>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2470.0480905256995!2d-1.2428787840199145!3d51.75044417967568!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48718e73c7fbcccd%3A0x7d42b497ec583bd2!2sRedbrick+House!5e0!3m2!1sen!2suk!4v1540294069847" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
</center>
</div>

</div>

### Booking a course at Visible Data's offices

<div class='row'>

<div class='col-md-6'>

If you've got all the information you need right now, then please do fill in the booking request form on this page.

We understand you probably have questions before wanting to book a course, so please do contact us via email: contact@visibledata.co.uk.

<!-- <center> -->
<!-- <iframe src="https://calendar.google.com/calendar/embed?showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=WEEK&amp;height=600&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=visibledata.co.uk_efsl7gt12rv29lms797atkh19k%40group.calendar.google.com&amp;color=%23A32929&amp;ctz=Europe%2FLondon" style="border:solid 1px #777" width="100%" height="600" frameborder="0" scrolling="no"></iframe> -->
<!-- </center> -->
<!--- Implement https://fullcalendar.io/docs/google-calendar -->

</div>

<div class='col-md-6' id="booking-form">

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfNaKpBiPCN4nOWG2HPrAJIjXt2cOJlq1gSkJzeW8xC4u48Bw/viewform?embedded=true" width="640" height="784" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

</div>

</div>

### Accessibility {#accessibility}

Accessibility for all is a core belief for Visible Data, and something we are constantly trying to improve. We acknowledge that adaptations will be needed for individual's specific needs. We therefore value both your requests and feedback to help us improve via email contact@visibledata.co.uk.

The information below pertains exclusively to our offices as a venue, for information about the accessibility of our training content please visit our [dedicated accessibility information page](../accessibility).

The Redbrick House building has step-free access at the rear entrance, through the car park that is accessed from Backfields (BS2 8QJ).

Training events are hosted in a dedicated room on the ground floor which is fully accessible for those who require a level access route.

Consultancy meetings are hosted either in the same room as the training events or else a room on the second floor which is currently only accessible via steps. When booking a room we will ask you if level access is required and make the appropriate booking.

#### Lifts

Currently, no lift access is provided.

#### Accessible toilets

There is only one accessible toilet. It is located on the ground floor and accessible to those that require a level access route.

#### Standard toilets

There are 3 standard toilets in the building, they are unisex. Toilets are in the stairwell on floors 1, 2 and 3.

#### Hearing support system

There are no hearing loops provided in the building.

#### Inaccessible Areas

The following areas are not accessible to those who require level access:

- All 3 standard toilets
- Meeting rooms "David Bowie" and "Zara Hadid". Visible Data will consult with you before booking these rooms.





