---
title: "Public training at Redbrick House"
description: "Public training at Redbrick House"
keywords: ["Training"]
---

<div class='row'>

<div class='col-sm-9'>

Our next training course in Bristol is a two day course scheduled for Monday 1st April, and focuses on **interactive data visualisation with R**.

<p>
  <a class="btn btn-success" data-toggle="collapse" href="#redbrick-group-training" role="button" aria-expanded="false" aria-controls="collapseExample" style='width:100%'>
    Course description
  </a>
</p>
<div class="collapse" id="redbrick-group-training">
  <div class="card card-body">

### Who is this course for?

This course is designed for those who want to create interactive data visualisations with R, including; charts, maps, choropleth, networks, graph and sankey diagrams. In this course you will learn how to:

- Reproducibly read data into R using the tidyverse
- Wrangle messy data from Excel files into tidy, analysable data with the tidyverse
- Design interactive dataviz to explore and understand your data

### How much R do I need to know?

This course is designed for both new and existing users of R. All the pre-requisite skills for creating the data visualisations will be taught in the two days. We've split tickets into new and existing users to save you time - no pre-course survey!

Your trainer (Martin John Hadley) has run this course for 3 years to over 500 students. Martin is confident that you won't be left behind if your new and will have plenty to learn if you're unfamiliar with the tidyverse and htmlwidgets.

### BYOD (Bring Your Own Device)

This course is BYOD. You must bring your own machine. This is because we want you to learn how to do things on your machine.

We're always happy when folks have a variety of Operating Systems (Windows, macOS and Linux) as it allows us to demonstrate just how reproducible and portable R code can be. We'll send you download instructions 3 days before the training event.

### Schedule
This is a two day course (2019/04/01 and 2019/04/02) in the dedicated training room at our offices in Bristol. The course venue is fully accessible for those requiring level access, please see our [accessibiltiy statement](#accessibility) for more information.

- Arrive 09:00 - 09:30 to tea, coffee and a friendly welcome
- Training starts at 09:30 both days
- A [free lunch from Pret-a-manger](http://pret-files.azureedge.net/pretamanger-uk/Pret_Delivers/Delivery_Lunch_Menu.pdf) is provided
- Training finishes at 16:30 both days

### Who is training us?
Martin John Hadley. Hello! You can find me on Twitter ([\@martinjhnhadley](http://twitter.com/martinjhnhadley)) and on [LinkedIn](https://www.linkedin.com/in/martinjohnhadley/).

I'm an RSE at University of Oxford where I teach R on a number of Masters programmes and at divisional level to PhD researchers, I also founded the [Interactive Data Network](http://idn.it.ox.ac.uk/) which uses Shiny to make research data more open and accessible.

For the past 4 years* I've been delivering in-person commercial training in R, data visualisation and Shiny across the UK. You can also find my on-demand courses on [LinkedIn Learning & Lynda.com](https://www.linkedin.com/learning/instructors/martin-john-hadley?u=2125562).

*prior to this I worked for 3 years as a consultant for Wolfram Research, where I used and taught Mathematica. But these days I've almost completely replaced Mathematica with R in my workflows.

<br>
<br>

  </div>
</div>

<div id="eventbrite-widget-container-56339694543"></div>

<script src="https://www.eventbrite.co.uk/static/widgets/eb_widgets.js"></script>

<script type="text/javascript">
    var exampleCallback = function() {
        console.log('Order complete!');
    };

    window.EBWidgets.createWidget({
        // Required
        widgetType: 'checkout',
        eventId: '56339694543',
        iframeContainerId: 'eventbrite-widget-container-56339694543',

        // Optional
        iframeContainerHeight: 550,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
    });
</script>

</div>

<div class='col-sm-3'>

<div style="width:100%; text-align:center;">
<center>
<iframe  src="https://www.eventbrite.co.uk/calendar-widget?eid=52007630222" frameborder="0" height="552" width="195" marginheight="0" marginwidth="0" scrolling="no" allowtransparency="true"></iframe>
</center>
</div>

</div>

</div>

<h3>Why attend a public course at our offices?</h3>

<ul>
<li>
**Public courses are great learning environments.** 
<br>
We really enjoy the diversity of experience and industries that public courses bring together, and our delegates have only ever been positive about..</li>
<li>
**We're located in Bristol City Centre.** 
<br>
Bristol has great transport links, it's also a beautiful and vibrant city to explore at the end of the training day.</li>
<li>
**Accessibility matters to us.**
<br>
Our training facilities have step-free access and we're happy to work with you and make reasonable adjustments. Read about our building's accessibility [below](#accessibility).</li>
<li>
**We use a dedicated, comfortable training room.**
<br>
We've set our max number at 15 to assure comfort, you will not be packed in line sardines.</li>
<li>
**All our training courses are BYOD (Bring Your Own Device).**
<br>
You'll learn how to do stuff with <strong>your</strong> (<i>work</i>) machine.</li>
<li>
**We've got extension cables for your laptops.**
<br>
You do need to bring your own chargers.</li>
<li>**There's coffee. And tea. And Wi-fi.**</li>
<li>**We provide lunch from Pret-A-Manger!**
<br>
Before the training day we'll agree what you'd like from the <a href='http://pret-files.azureedge.net/pretamanger-uk/Pret_Delivers/Delivery_Lunch_Menu.pdf' target='_blank'>lunch platter menu.</a>
</li>
</ul>

<h3>What are the benefits of off-site training?</h3>

<ul>

<li>If your team is distributed across multiple sites it can be really difficult to decide where to hold training on company sites. 
<br>
<strong>Dedicated off-site training sites are neutral territory (and Visible Data has <i>lots</i> of hotels nearby `r emo::ji("wave")`)</strong></li>


<li>Re-purposing a conference room at your office for multiple day training courses is often difficult, there's a temptation to break the training up over multiple weeks or over lunch.
<br>
<strong>Using a dedicated training space means you can easily book dedicated multi-day courses.</strong></li>

<li>Using a re-purposed conference room in your building is not going to put your team in the mindset to learn, folks may well be distracted thinking about what they're usually in the room for.
<br>
<strong>Off-site training helps put your team in the mindset to learn.</strong></li>

<li>Training on-site is often disrupted by colleagues being able to physically barge into rooms and "just check one thing."
<br>
<strong>Distractions are massively reduced when using a dedicated off-site training space.</strong></li>

</ul>

### Getting to Visible Data's offices in Bristol

Our office is a short walk from Bristol City Centre. There is accessible parking and step-free access at the rear of the building (use Post Code BS2 8AQ). For folks looking for non-accessible parking, these are the best options:

- [NCP Parking @ BS1 3LJ (£25/day)](https://www.ncp.co.uk/find-a-car-park/car-parks/bristol-st-james-barton/)
- [Cabot Circus Parking @ BS2 9AB](https://m.cabotcircus.com/visitor-info/parking)

<center>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2470.0480905256995!2d-1.2428787840199145!3d51.75044417967568!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48718e73c7fbcccd%3A0x7d42b497ec583bd2!2sRedbrick+House!5e0!3m2!1sen!2suk!4v1540294069847" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
</center>

### Accessibility {#accessibility}

Accessibility for all is a core belief for Visible Data, and something we are constantly trying to improve. We acknowledge that adaptations will be needed for individual's specific needs. We therefore value both your requests and feedback to help us improve via email contact@visibledata.co.uk.

The information below pertains exclusively to our offices as a venue, for information about the accessibility of our training content please visit our [dedicated accessibility information page](../accessibility).

The Redbrick House building has step-free access at the rear entrance, through the car park that is accessed from Backfields (BS2 8QJ).

Consultancy meetings are hosted either in the same room as the training events or else a room on the second floor which is currently only accessible via steps. When booking a room we will ask you if level access is required and make the appropriate booking.

#### Lifts

Currently, no lift access is provided.

#### Accessible toilets

There is only one accessible toilet. It is located on the ground floor and accessible to those that require a level access route.

#### Standard toilets

There are 3 standard toilets in the building, they are unisex. Toilets are in the stairwell on floors 1, 2 and 3.

#### Hearing support system

There are no hearing loops provided in the building.

#### Inaccessible Areas

The following areas are not accessible to those who require level access:

- All 3 standard toilets
- Meeting rooms "David Bowie" and "Zara Hadid". Visible Data will consult with you before booking these rooms.





