---
title: "Advent of Code 2024 - Day 3"
date: '2024-12-14'
execute:
  freeze: true
  message: false
  warning: false
  echo: true
engine: knitr
filters:
  - line-highlight
---

```{r}
#| include: false
library("cjhRutils")
```

::: {.callout-note appearance="simple"}

# You really shouldn't be reading this before you've had a go yourself!

:::

# R

Let's try with test data:

```{r}
library("tidyverse")

data_test <- "xmul(2,4)%&mul[3,7]!@^do_not_mul(5,5)+mul(32,64]then(mul(11,8)mul(8,5))"

extracted_operations <- str_extract_all(data_test, "mul[(]\\d{1,3},\\d{1,3}[)]")[[1]] %>% 
  paste(collapse = "") %>% 
  str_extract_all(.,"\\d{1,3},\\d{1,3}") %>% 
  map(~str_replace(., ",", "*")) %>% 
  .[[1]] 


eval(parse(text = paste(extracted_operations, collapse = "+")))
```

And the real data

```{r}
data_real <- paste(read_lines(quarto_here("input.txt")), collapse = "")

extracted_operations <- str_extract_all(data_real, "mul[(]\\d{1,3},\\d{1,3}[)]")[[1]] %>% 
  paste(collapse = "") %>% 
  str_extract_all(.,"\\d{1,3},\\d{1,3}") %>% 
  map(~str_replace(., ",", "*")) %>% 
  .[[1]] 

eval(parse(text = paste(extracted_operations, collapse = "+")))
```

